---
kind: pipeline
name: default

steps:
  - name: Test apllication
    image: node:12.13.1
    commands:
      - yarn install
      - yarn lint
      - yarn test || echo tests are not ok

  - name: Republish package on npmjs
    image: node:12.13.1
    environment:
      REPO_NAME: ${DRONE_REPO}
      NPM_LOGIN:
        from_secret: npmjs_login
      NPM_PASS:
        from_secret: npmjs_pass
      NPMJS_TOKEN:
        from_secret: npmjs_token
      GITHUB_API_KEY:
        from_secret: kite_bot_key
    commands:
      - git config --global user.name "kite-bot"
      - git config --global user.email "kite-bot@heliostech.fr"
      - git remote add authenticated-origin https://kite-bot:$GITHUB_API_KEY@github.com/${DRONE_REPO}
      - git fetch
      - echo "//registry.npmjs.org/:_authToken=$NPMJS_TOKEN" > .npmrc
      - sh scripts/version_bump.sh $NPM_LOGIN $NPM_PASS
      - git add package.json
      - git commit --amend --no-edit

  - name: "Bump & Tag"
    image: quay.io/openware/sdk-citools:2.3.1
    environment:
      BRANCH_NAME: ${DRONE_BRANCH}
      REPO_NAME: ${DRONE_REPO}
      GITHUB_API_KEY:
        from_secret: kite_bot_key
    commands:
      - BUNDLE_GEMFILE=/sdk/Gemfile bundle exec rake --rakefile=/sdk/Rakefile ci:prebuild

trigger:
  event:
  - push

image_pull_secrets:
  - dockerconfigjson

